export const BLACK_TWITTER = [
  { phrase: "He needs some milk", acronym: "HNSM" },
  { phrase: "Where's the lie?", acronym: "WTL?" },
  { phrase: "Not all heros wear capes", acronym: "NAHWC" },
  { phrase: "I'm rooting for everybody black", acronym: "IRFEB" },
  { phrase: "We have no choice but to stan", acronym: "WHNCBTS" },
  { phrase: "Whew child the ghetto", acronym: "WCTG" },
  { phrase: "She did what she had to do", acronym: "SDWSHTD" },
  { phrase: "We all we got", acronym: "WAWG" },
  { phrase: "Yet here we are", acronym: "YHWA" },
  { phrase: "Twitter do your thing", acronym: "TDYT" },
  { phrase: "That ain't it", acronym: "TAI" },
  { phrase: "Sorry to this man", acronym: "STTM" },
  { phrase: "Spill the tea", acronym: "STT" },
  { phrase: "Shoot your shot", acronym: "SYS" },
  { phrase: "Secure the bag", acronym: "STB" },
  { phrase: "I hate it here", acronym: "IHIH" },
  { phrase: "It's above me now", acronym: "IAMN" },
  { phrase: "Your fav could never", acronym: "YFCN" },
  { phrase: "You gon' learn today", acronym: "YGLT" },
  { phrase: "Stop clout chasing", acronym: "SCC" },
  { phrase: "I said what I said", acronym: "ISWIS" },
  { phrase: "What you not gon' do", acronym: "WYNGD" },
  { phrase: "Oh you tried it", acronym: "OYTI" },
  { phrase: "Out here living", acronym: "OHL" },
  { phrase: "I would like to see it", acronym: "IWLTSI" },
  { phrase: "Whose man is this?", acronym: "WMIT?" },
  { phrase: "This can't be life", acronym: "TCBL" },
  { phrase: "Make it make sense", acronym: "MIMS" },
  { phrase: "I don't know who needs to hear this but", acronym: "IDKWNTHTB" },
  { phrase: "I can't with you", acronym: "ICWY" },
  { phrase: "But did you die?", acronym: "BDYD?" },
  { phrase: "No shade", acronym: "NS" },
  { phrase: "I got time today", acronym: "IGTT" },
  { phrase: "No new friends", acronym: "NNF" },
  { phrase: "Ain't nobody got time for that", acronym: "ANGTFT" },
  { phrase: "Netfilx and Chill", acronym: "NAC" },
  { phrase: "Keep that same energy", acronym: "KTSE" },
  { phrase: "You hate to see it", acronym: "YHTSI" },
  { phrase: "So this what we doing?", acronym: "STWWD?" },
  { phrase: "God I see what you've done for others", acronym: "GISWYDFO" },
  { phrase: "You did that", acronym: "YDT" },
  {
    phrase: "You should've just sat there and ate your food",
    acronym: "YSJSTAAYF",
  },
  { phrase: "I'm here for it", acronym: "IHFI" },
  { phrase: "I love this song", acronym: "ILTS" },
  { phrase: "We tried to tell y'all", acronym: "WTTTY" },
  { phrase: "Where they do that at?", acronym: "WTDTA?" },
  { phrase: "Stay in your lane", acronym: "SIYL" },
  { phrase: "I'm old enough to remember when", acronym: "IOETRW" },
  { phrase: "Questions that need answers", acronym: "QTNA" },
  { phrase: "Why are we like this", acronym: "WAWLT?" },
];
