export const CHURCH = [
  { phrase: "I can't get no help up in here", acronym: "ICGNHUIH" },
  { phrase: "Get ready, get ready, get ready", acronym: "GRGRGR" },
  { phrase: "I'm getting ready to close", acronym: "IGRTC" },
  {
    phrase:
      "If you can hang out on Saturday night you can get up on Sunday morning",
    acronym: "IYCHOOSNYCGUOSM",
  },
  { phrase: "He woke me up clothed in my right mind", acronym: "HWMUCIMRM" },
  {
    phrase: "The devil thought he had me but I got away",
    acronym: "TDTHHMBIGA",
  },
  {
    phrase: "He's been better to me than I've been to myself",
    acronym: "HBBTMTIBTM",
  },
  { phrase: "He brought me from a mighty long way", acronym: "HBMFAMLW" },
  { phrase: "Let the Lord use you", acronym: "LTLUY" },
  { phrase: "The devil is a liar", acronym: "TDIAL" },
  { phrase: "Bless her heart", acronym: "BHH" },
  { phrase: "You have not because you ask not", acronym: "YHNBYAN" },
  { phrase: "Won't he do it?", acronym: "WHDI?" },
  { phrase: "You better preach", acronym: "YBP" },
  {
    phrase: "Every good and perfect gift comes from above",
    acronym: "EGAPGCFA",
  },
  { phrase: "Turn to your neighbor and say neighbor", acronym: "TTYNASN" },
  {
    phrase: "First giving honor to God who is the head of my life",
    acronym: "FGHTGWITHOML",
  },
  { phrase: "Fix it Jesus", acronym: "FIJ" },
  {
    phrase: "He's a mother to the motherless and a father to the fatherless",
    acronym: "HAMTTMAAFTTF",
  },
  {
    phrase: "God is good all the time and all the time God is good",
    acronym: "GIGATTAATTGIG",
  },
  { phrase: "God knows my heart", acronym: "GKMH" },
  {
    phrase: "Weeping may endure for a night, but joy comes in the morning",
    acronym: "WMEFANBJCITM",
  },
  { phrase: "God works in mysterious ways", acronym: "GWIMW" },
  { phrase: "I could've been dead sleeping in my grave", acronym: "ICBDSIMG" },
  { phrase: "Not today Satan", acronym: "NTS" },
  { phrase: "I'm blessed and higly favored", acronym: "IBAHF" },
  {
    phrase: "I don't know what you came to do but I came to praise the Lord",
    acronym: "IDKWYCTDBICTPTL",
  },
  { phrase: "That ain't nothing but the devil", acronym: "TANBTD" },
  { phrase: "I just stopped by to tell you", acronym: "IJSBTTY" },
  { phrase: "Is there one?", acronym: "ITO?" },
  { phrase: "You better sang", acronym: "YBS" },
  { phrase: "I know it was the blood", acronym: "IKIWTB" },
  { phrase: "Let the church say amen", acronym: "LTCSA" },
  {
    phrase:
      "This is the day the Lord has made, we will rejoice and be glad in it",
    acronym: "TITDTLHMWWRABGII",
  },
  { phrase: "I love the Lord he heard my cry", acronym: "ILTLHHMC" },
  { phrase: "Please give to the builing fund", acronym: "PGTTBF" },
  { phrase: "Please govern yourselves accordingly", acronym: "PGYA" },
  { phrase: "It's not over until God says it's over", acronym: "INOUGSIO" },
  {
    phrase: "Saved sanctified and filled with the Holy Ghost",
    acronym: "SSAFWTHG",
  },
  { phrase: "Please stand for the reading of the word", acronym: "PSFTROTW" },
  { phrase: "You can do better than that", acronym: "YCDBTT" },
  { phrase: "It's offering time", acronym: "IOT" },
  { phrase: "Tie my bow tie untie my bow tie", acronym: "TMBTUMBT" },
  {
    phrase: "Life and death is in the power of the tongue",
    acronym: "LADIITPOTT",
  },
  { phrase: "The Lord loves a cheerful giver", acronym: "TLLACG" },
  { phrase: "Tell the truth shame the devil", acronym: "TTTSTD" },
  { phrase: "The rocks will cry out", acronym: "TRWCO" },
  { phrase: "No test, no tesitmony", acronym: "NTNT" },
  { phrase: "He didn't have to do it but he did", acronym: "HDHTDIBHD" },
  { phrase: "Pray for me he's not through with me yet", acronym: "PFMHNTWMY" },
];
