export const DAILY_SAYINGS = [
  { phrase: "Everybody and they momma in here", acronym: "EATMIH" },
  { phrase: "At the end of the day", acronym: "ATEOTD" },
  { phrase: "Don't be petty", acronym: "DBP" },
  { phrase: "You ain't said nothing but a word", acronym: "YASNBAW" },
  { phrase: "Out on a limb", acronym: "OOAL" },
  { phrase: "Do you see where I'm coming from?", acronym: "DYSWICF?" },
  { phrase: "I could care less", acronym: "ICCL" },
  { phrase: "You had one job", acronym: "YHOJ" },
  { phrase: "Now mind you", acronym: "NMY" },
  { phrase: "No one lives here by that name", acronym: "NOLHBTN" },
  { phrase: "This, that, and the third", acronym: "TTATT" },
  { phrase: "Help me, help me", acronym: "HMHM" },
  { phrase: "When it's all said and done", acronym: "WIASAD" },
  { phrase: "I'm just trying to be like you", acronym: "IJTBLY" },
  { phrase: "First of all", acronym: "FOA" },
  { phrase: "How much you trying to bet?", acronym: "HMYTTB?" },
  { phrase: "It's not you it's me", acronym: "INYIM" },
  { phrase: "Who all gon' be there?", acronym: "WAGBT?" },
  { phrase: "I just think it's funny how", acronym: "IJTIFH" },
  { phrase: "You got the right one", acronym: "YGTRO" },
  { phrase: "The out here today", acronym: "TOHT" },
  { phrase: "Are we there yet?", acronym: "AWTY?" },
  { phrase: "And that's that on that", acronym: "ATTOT" },
  { phrase: "I hope this finds you well", acronym: "IHTFYW" },
  { phrase: "Real G's move in silence", acronym: "RGMIS" },
  { phrase: "Aight so boom", acronym: "ASB" },
  { phrase: "Alright then, be like that", acronym: "ATBLT" },
  { phrase: "I don't know what to tell you", acronym: "IDKWTTY" },
  { phrase: "You better than me", acronym: "YBTM" },
  { phrase: "Sounds like a plan", acronym: "SLAP" },
  { phrase: "Don't I know you from somewhere", acronym: "DIKYFS?" },
  { phrase: "You could've fooled me", acronym: "YCFM" },
  { phrase: "You can get these hands", acronym: "YCGTH" },
  { phrase: "You doing the most", acronym: "YDTM" },
  { phrase: "You got me on speaker?", acronym: "YGMOS?" },
  { phrase: "You probably don't remember me do you?", acronym: "YPDRMDY" },
  { phrase: "Run me my money", acronym: "RMMM" },
  { phrase: "You by yourself?", acronym: "YBY?" },
  { phrase: "Who you telling", acronym: "WYT" },
  { phrase: "I'm ready when you are", acronym: "IRWYA" },
  { phrase: "It is what it is", acronym: "IIWII" },
  { phrase: "Not my cup of tea", acronym: "NMCOT" },
  { phrase: "You ain't never lied", acronym: "YANL" },
  { phrase: "It's right up the street", acronym: "IRUTS" },
  { phrase: "It's the principle", acronym: "ITP" },
  { phrase: "The truth of the matter is", acronym: "TTOTMI" },
  { phrase: "I'll be there in five minutes", acronym: "IBTIFM" },
  { phrase: "If you like it I love it", acronym: "IYLIILI" },
  { phrase: "If you say so", acronym: "IYSS" },
  { phrase: "Keep my name out your mouth", acronym: "KMNOYM" },
  { phrase: "Let me call you right back", acronym: "LMCYRB" },
  { phrase: "Out of sight out of mind", acronym: "OOSOOM" },
  { phrase: "Per my last email", acronym: "PMLE" },
  {
    phrase: "The good Lord willing and the creek don't rise",
    acronym: "TGLWATCDR",
  },
  { phrase: "Ask me if I care", acronym: "AMIIC" },
];
