export const FAMILY_FRIENDS = [
  { phrase: "Because I said so", acronym: "BISS" },
  { phrase: "I got eyes in the back of my head", acronym: "IGEITBOMH" },
  { phrase: "Closed mouths don't get fed", acronym: "CMDGF" },
  {
    phrase: "All in the Kool-aid and don't know the flavor",
    acronym: "AITKADKTF",
  },
  { phrase: "Do I look like Boo Boo the fool to you?", acronym: "DILLBBTFTY" },
  { phrase: "Do it and see what happens", acronym: "DIASWH" },
  { phrase: "You play too much", acronym: "YPTM" },
  { phrase: "If I'm lying I'm flying", acronym: "IILIF" },
  { phrase: "After everything I did for you?", acronym: "AEIDFY?" },
  { phrase: "You look just like your momma", acronym: "YLJLYM" },
  {
    phrase: "I brought you in to this world and I'll take you out",
    acronym: "IBYITWAITYO",
  },
  { phrase: "Do you hear me calling you?", acronym: "DYHMCY?" },
  {
    phrase: "When we get in the store don't touch nothing",
    acronym: "WWGITSDTN",
  },
  { phrase: "You put your foot in this", acronym: "YPYFIT" },
  { phrase: "Who are you talking to", acronym: "WAYTT?" },
  { phrase: "I got Indian in my family", acronym: "IGIIMF" },
  { phrase: "Keep your hands to yourself", acronym: "KYHTY" },
  {
    phrase: "What goes on in this house stays in this house",
    acronym: "WGOITHSITH",
  },
  { phrase: "Take the chicken out the freezer", acronym: "TTCOTF" },
  { phrase: "Have you lost your ever loving mind?", acronym: "HYLYELM?" },
  { phrase: "I used to change your diapers", acronym: "IUTCYD" },
  {
    phrase: "You have to work twice as hard to be considered half as good",
    acronym: "YHTWTAHTBCHAG",
  },
  { phrase: "I'm scared of you", acronym: "ISOY" },
  { phrase: "Soak it in some epsom salt", acronym: "SIISES" },
  { phrase: "Don't make me say it again", acronym: "DMMSIA" },
  { phrase: "Do I look like I was born yesterday?", acronym: "DILLIWBY?" },
  { phrase: "Drink some ginger ale", acronym: "DSGA" },
  { phrase: "Don't make me have to come in there", acronym: "DMMHTCIT" },
  { phrase: "Those were the good ole days", acronym: "TWTGOD" },
  { phrase: "Fix your face", acronym: "FYF" },
  {
    phrase: "Don't make me embarrass you in front of your friends",
    acronym: "DMMEYIFOYF",
  },
  { phrase: "Did I stutter?", acronym: "DIS?" },
  { phrase: "Go get my belt", acronym: "GGMB" },
  { phrase: "Do I need to pull this car over?", acronym: "DINTPTCO?" },
  { phrase: "Go somewhere and sit down", acronym: "GSASD" },
  { phrase: "I had a dream about fish", acronym: "IHADAF" },
  { phrase: "That's my play cousin", acronym: "TMPC" },
  { phrase: "Ah he he hell", acronym: "AHHH" },
  {
    phrase: "Stop crying before I give you something to cry about",
    acronym: "SCBIGYSTCA",
  },
  { phrase: "If it was a snake it would've bit you", acronym: "IIWASIWBY" },
  { phrase: "Either you in or you out", acronym: "EYIOYO" },
  { phrase: "You smell like outside", acronym: "YSLO" },
  { phrase: "I wish you would", acronym: "IWYW" },
  { phrase: "I remember when you were this tall", acronym: "IRWYWTT" },
  { phrase: "I'm tired of talking", acronym: "ITOT" },
  { phrase: "Please act like you got some home training", acronym: "PALYGSHT" },
  { phrase: "Sleep tight don't let the bed bugs bite", acronym: "STDLTBBB" },
  { phrase: "Who made the potato salad?", acronym: "WMTPS?" },
  { phrase: "Don't have me out here looking stupid", acronym: "DHMOHLS" },
  { phrase: "Check your tone", acronym: "CYT" },
  { phrase: "Stay out of grown folks business", acronym: "SOOGFB" },
  { phrase: "What had happened was", acronym: "WHHW" },
  { phrase: "We got food at home", acronym: "WGFAH" },
  { phrase: "You got McDonald's money", acronym: "YGMM?" },
  { phrase: "I'm not one of your little friends", acronym: "INOOYLF" },
];
