export const CULTURE_TAGS_PHRASES = {
  "Black Twitter": [
    { phrase: "Stay In Your Lane", acronym: "SIYL" },
    { phrase: "That's On Period", acronym: "TOP" },
    { phrase: "Not Today Satan", acronym: "NTS" },
    { phrase: "It's Giving What It's Supposed To Give", acronym: "IGWISG" },
    { phrase: "No Cap No Lie", acronym: "NCNL" },
    { phrase: "We Outside", acronym: "WO" },
    { phrase: "Put Some Respek On My Name", acronym: "PSROMN" },
  ],
  Church: [
    { phrase: "Bless The Lord Oh My Soul", acronym: "BTLOMS" },
    { phrase: "God Is Good All The Time", acronym: "GIGATT" },
    { phrase: "His Eye Is On The Sparrow", acronym: "HEIOTS" },
    { phrase: "By His Stripes We Are Healed", acronym: "BHSWAH" },
    { phrase: "Fix It Jesus", acronym: "FIJ" },
    { phrase: "The Lord Will Make A Way", acronym: "TLWMAW" },
    { phrase: "Give Me A Praise Break", acronym: "GMAPB" },
  ],
  "Daily Sayings": [
    { phrase: "What Goes Around Comes Around", acronym: "WGACA" },
    { phrase: "You Only Live Once", acronym: "YOLO" },
    { phrase: "It Is What It Is", acronym: "IIWII" },
    {
      phrase: "Do Unto Others As You Would Have Done To You",
      acronym: "DUOAYWHDTY",
    },
    { phrase: "Mind Your Own Business", acronym: "MYOB" },
    { phrase: "Actions Speak Louder Than Words", acronym: "ASLTW" },
    { phrase: "Keep It One Hundred", acronym: "KI100" },
  ],
  "Family & Friends": [
    { phrase: "You Got McDonald's Money?", acronym: "YGMM?" },
    { phrase: "We Don't Do That In This House", acronym: "WDDTITH" },
    { phrase: "Because I Said So", acronym: "BISS" },
    { phrase: "Go Ask Your Father", acronym: "GAYF" },
    { phrase: "I'll Give You Something To Cry About", acronym: "IGYSTCA" },
    { phrase: "Clean Up Your Room Before Company Comes", acronym: "CUYRBC" },
    { phrase: "Don't Make Me Come In There", acronym: "DMMCIT" },
  ],
  "Songs & Lyrics": [
    { phrase: "Started From The Bottom Now We Here", acronym: "SFTBNWH" },
    { phrase: "All Eyez On Me", acronym: "AEOM" },
    { phrase: "No New Friends", acronym: "NNF" },
    { phrase: "Running Through The Six With My Woes", acronym: "RTTSWMW" },
    { phrase: "I Used To Love Her", acronym: "IUTLH" },
    { phrase: "What's Going On", acronym: "WGO" },
    { phrase: "Killing Me Softly With His Song", acronym: "KMSWHS" },
  ],
  "TV & Film": [
    { phrase: "You Are The Weakest Link Goodbye", acronym: "YATWLG" },
    { phrase: "Is That Your Final Answer", acronym: "ITYFA" },
    {
      phrase: "Come On Down You Are The Next Contestant",
      acronym: "CODYANTNC",
    },
    { phrase: "They Did The Monster Mash", acronym: "TDTMM" },
    { phrase: "To Infinity And Beyond", acronym: "TIAB" },
    { phrase: "Why So Serious", acronym: "WSS" },
    { phrase: "I'll Be Back", acronym: "IBB" },
  ],
  "Words to Live By": [
    { phrase: "Everything Happens For A Reason", acronym: "EHFAR" },
    { phrase: "Live Laugh Love", acronym: "LLL" },
    { phrase: "Work Hard Play Hard", acronym: "WHPH" },
    { phrase: "Be The Change You Wish To See", acronym: "BTCYWTS" },
    { phrase: "Count Your Blessings Not Your Problems", acronym: "CYBNPY" },
    { phrase: "Speak Life Into Your Situation", acronym: "SLIYS" },
    { phrase: "Protect Your Peace At All Costs", acronym: "PYPAAC" },
  ],
};
