export const TV_FILM = [
  { phrase: "One Fish, Two Fish, Red Fish, Blue Fish", acronym: "OFTFRFBF" },
  { phrase: "Did I do that?", acronym: "DIDT?" },
  { phrase: "When they see us", acronym: "WTSU" },
  { phrase: "That boy good!", acronym: "TBG" },
  { phrase: "Puff, puff, pass", acronym: "PPP" },
  { phrase: "I hate you, Jody!", acronym: "IHYJ" },
  { phrase: "Why do fools fall in love?", acronym: "WDFFIL?" },
  {
    phrase: "We didn't land on Plymouth Rock, Plymouth Rock landed on us!",
    acronym: "WDLOPRPRLOU",
  },
  { phrase: "Got the draws!!!", acronym: "GTD" },
  { phrase: "Diary of a mad black woman", acronym: "DOAMBW" },
  { phrase: "We ride together, we die together", acronym: "WRTWDT" },
  { phrase: "Punks jump up to get beat down", acronym: "PJUTGBD" },
  { phrase: "Man my grandma gave me that chain!", acronym: "MMGGMTC" },
  { phrase: "You ain't got no job Tommie!", acronym: "YAGNJT" },
  { phrase: "You told Harpo to beat me?", acronym: "YTHTBM?" },
  { phrase: "How you get fired on your day off?", acronym: "HYGFOYDO?" },
  { phrase: "In West Philidelphia born and raised", acronym: "IWPBAR" },
  { phrase: "What's love got to do with it?", acronym: "WLGTDWI?" },
  { phrase: "Homie don't play that!", acronym: "HDPT" },
  { phrase: "Show me the money!!", acronym: "SMTM" },
  { phrase: "A low down dirty shame", acronym: "ALDDS" },
  { phrase: "The Oprah Winfrey Show", acronym: "TOWS" },
  { phrase: "Ain't nobody coming to see you, Otis!", acronym: "ANCTSYO" },
  { phrase: "She's your queen to be", acronym: "SYQTB" },
  { phrase: "See Daddy sinners got souls too", acronym: "SDSGST" },
  { phrase: "How Stella got her groove back", acronym: "HSGHGB" },
  { phrase: "We don't die we multiply", acronym: "WDDWM" },
  { phrase: "Make the money, don't let it make you", acronym: "MTMDLIMY" },
  {
    phrase: "You is kind, You is smart, You is important",
    acronym: "YIKYISYII",
  },
  {
    phrase: "I don't have to do nothin' but stay black and die",
    acronym: "IDHTDNBSBAD",
  },
  { phrase: "You goin' eat your cornbread?", acronym: "YGEYC?" },
  { phrase: "You sho is ugly", acronym: "YSIU" },
  { phrase: "Is this your King?", acronym: "ITYK?" },
  { phrase: "How to be a player", acronym: "HTBAP" },
  { phrase: "When did you fall in love with hip hop?", acronym: "WDYFILWHH?" },
  { phrase: "You got to coordinate", acronym: "YGTC" },
  {
    phrase: "Hey Sal, How come there ain't no brothers on the wall?",
    acronym: "HSHCTANBOTW",
  },
  { phrase: "In Living Color", acronym: "ILC" },
  { phrase: "The Princess and the Frog", acronym: "TPATF" },
  { phrase: "It's a thin line between love and hate", acronym: "IATLBLAH" },
  {
    phrase: "I ain't one to gossip so you ain't heard that from me",
    acronym: "IAOTGSYAHTFM",
  },
  { phrase: "Pass the peas like we used to do", acronym: "PTPLWUTD" },
  { phrase: "You ain't got to lie Craig", acronym: "YAGTLC" },
  {
    phrase:
      "Don't be a menance to South Central while drinking your juice in the hood",
    acronym: "DBAMTSCWDYJITH",
  },
  {
    phrase: "His momma named him Clay, I'mma call him Clay",
    acronym: "HMNHCICHC",
  },
];
