export const WORDS_TO_LIVE_BY = [
  { phrase: "When there's a will, there's a way", acronym: "WTAWTAW" },
  { phrase: "One monkey don't stop no show", acronym: "OMDSNS" },
  { phrase: "Practice what you preach", acronym: "PWYP" },
  { phrase: "Because of them we can", acronym: "BOTWC" },
  { phrase: "Black is beautiful", acronym: "BIB" },
  { phrase: "When you know better you do better", acronym: "WYKBYDB" },
  {
    phrase: "You never miss your water until your well runs dry",
    acronym: "YNMYWUYWRD",
  },
  { phrase: "Don't put all your eggs in one basket", acronym: "DPAYEIOB" },
  { phrase: "Everything happens for a reason", acronym: "EHFAR" },
  { phrase: "What goes around comes around", acronym: "WGACA" },
  { phrase: "Don't sweat nothing, won't be nothing", acronym: "DSNWBN" },
  { phrase: "All shut eyes ain't sleep", acronym: "ASEAS" },
  {
    phrase: "Proper planning prevents piss poor performance",
    acronym: "PPPPPP",
  },
  { phrase: "All that glitters ain't gold", acronym: "ATGAG" },
  { phrase: "Beggars can't be choosers", acronym: "BCBC" },
  { phrase: "Be careful what you wish for", acronym: "BCWYWF" },
  { phrase: "The early bird gets the worm", acronym: "TEBGTW" },
  {
    phrase: "What's done in the dark always comes to light",
    acronym: "WDITDACTL",
  },
  {
    phrase: "The grass is always greener on the other side",
    acronym: "TGIAGOTOS",
  },
  { phrase: "Blood is thicker than water", acronym: "BITTW" },
  { phrase: "Two wrongs don't make a right", acronym: "TWDMAR" },
  { phrase: "Don't come for me unless I send for you", acronym: "DCFMUISFY" },
  { phrase: "Birds of a feather flock together", acronym: "BOAFFT" },
  {
    phrase: "When someone shows you who they are believe them",
    acronym: "WSSYWTABT",
  },
  { phrase: "If you know you know", acronym: "IYKYK" },
  { phrase: "I can do bad all by myself", acronym: "ICDBABM" },
  { phrase: "One man's trash is another man's treasure", acronym: "OMTIAMT" },
  { phrase: "All money ain't good money", acronym: "AMAGM" },
  { phrase: "A hit dog will holler", acronym: "AHDWH" },
  { phrase: "My name Bennett and I ain't in it", acronym: "MNBAIAII" },
  { phrase: "Life is too short", acronym: "LITS" },
  {
    phrase: "If you can't stand the heat, get out the kitchen",
    acronym: "IYCSTHGOTK",
  },
  { phrase: "If it ain't broke, don't fix it", acronym: "IIABDFI" },
  { phrase: "Black don't crack", acronym: "BDC" },
  { phrase: "Scared money don't make money", acronym: "SMDMM" },
  { phrase: "It's cheaper to keep her", acronym: "ICTKH" },
  { phrase: "Home is where the heart is", acronym: "HIWTHI" },
  { phrase: "God don't like ugly", acronym: "GDLU" },
  { phrase: "All skinfolk ain't kinfolk", acronym: "ASAK" },
  { phrase: "You gotta do what's best for you", acronym: "YGDWBFY" },
  { phrase: "Don't talk about it be about it", acronym: "DTAIBAI" },
  { phrase: "Don't judge a book by it's cover", acronym: "DJABBIC" },
  { phrase: "Damned if you do, Damned if you don't", acronym: "DIYDDIYD" },
  { phrase: "Don't believe everything you hear", acronym: "DBEYH" },
  { phrase: "Better safe than sorry", acronym: "BSTS" },
];
